#: include kv/menu.kv
#: include kv/kreator.kv
#: include kv/person.kv
#: include kv/detain.kv

GridLayout:
    cols: 2
    ScreenManager:
        id: screen_manager
        Menu:
            name: "menu_screen"
            id: menu_screen
        Creator:
            name: "kreator"
            id: kreator
        Person:
            name: "person"
            id: person
        Detain:
            name: "Detain"
            id: Detain